#!/bin/sh
BASEDIR=$(dirname $0)
source=$(readlink "$BASEDIR/pre-commit")

if [[ -n "$source" ]]; then
    BASEDIR=$(echo $source|sed 's/pre-commit$//g')
fi

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

exec "$BASEDIR"/android-check.py -t staged
